#index:
#    path: /
#    controller: App\Controller\DefaultController::index

product_list:
    path: /products
    controller: App\Controller\ProductController::products
    methods: GET

product_show:
    path: '/products/{productId}'
    controller: App\Controller\ProductController::showProduct
    methods: GET

products_in_category:
    path: '/category/{categoryId}/products'
    controller: 'App\Controller\ProductController::productsInCategory'
    methods: ['GET']

filtered_products:
    path: '/filtered-products'
    controller: 'App\Controller\ProductController::filteredProducts'
    methods: ['GET']

create_order:
    path: '/orders/new'
    controller: 'App\Controller\ProductController::createOrder'
    methods: ['POST']